import type { Metadata } from "next";
import { Gilda_Display, Source_Sans_3 } from "next/font/google";
import "./globals.css";

const gildadisplay = Gilda_Display({
  variable: "--font-gilda-display",
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  preload: true,
});

const sourcesans3 = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preconnect to Google Fonts for faster loading */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${gildadisplay.variable} ${sourcesans3.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
